In [4]:
#Question 1: Create a 4X2 integer array and Prints its attributes
#• The shape of an array.
#• Array dimensions.
#• The Length of each element of the array in bytes

import numpy as np
a=np.random.randint(1,10,(4,2))
a

array([[8, 6],
       [8, 6],
       [7, 8],
       [5, 2]])

In [5]:
a.shape

(4, 2)

In [6]:
a.ndim

2

In [7]:
a.size

8

In [8]:
a.itemsize

4

In [9]:
#Question 2: Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10
z=np.random.randint(100,200,(5,2))
z

array([[175, 137],
       [183, 171],
       [156, 193],
       [116, 144],
       [180, 170]])

In [13]:
#Question 3: Following is the provided numpy array. return array of items in the third column from all rows.
p=np.array([[1,2,3],[4,5,6],[7,8,9]])
p

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
p[0:,2:]

array([[3],
       [6],
       [9]])

In [2]:
import numpy as np

In [19]:
#Question 4: Following is the given numpy array return array of odd rows and even columns
x=np.random.randint(10,50,(5,4))
x

array([[35, 33, 16, 16],
       [24, 26, 19, 17],
       [14, 43, 29, 25],
       [24, 42, 39, 26],
       [44, 11, 46, 31]])

In [22]:
x[0::2,1::2]

array([[33, 16],
       [43, 25],
       [11, 31]])

In [27]:
#Question 5: Split the array into four equal-sized sub-arrays
#Note: Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.

g=np.arange(10,34,1)
g

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33])

In [28]:
g.reshape(8,3)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [35]:
s = np.split(g, 4) 
s

[array([10, 11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20, 21]),
 array([22, 23, 24, 25, 26, 27]),
 array([28, 29, 30, 31, 32, 33])]

In [4]:
# Question 6: Create an 8x8 matrix and fill it with a checkerboard pattern
n=np.ones((3,3))
n=np.zeros((8,8),dtype=int)
n[1::2,::2]=1
n[::2,1::2]=1
n

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])